version: "3.7"

networks:
  default:
    name: url-shortener

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      default:
        aliases:
          - web
 