version: "3.7"

networks:
  default:
    name: url-shortener-tests

services:
  db-tests:
    image: mongo:4.4
    container_name: web-db-tests
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      default:
        aliases:
          - db
  api-tests:
    container_name: web-api-tests
    build:
      context: ../api/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      NODE_PORT: 80
      DB_USER: 'root'
      DB_PASSWORD: 'example'
      DB_URL: mongodb://root:example@db:27017/url-db
    depends_on:
      - db-tests
    networks:
      default:
        aliases:
          - api
  web-tests:
    container_name: web-web-tests
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-tests
    entrypoint:
      yarn test
    networks:
      default:
        aliases:
          - web
 
 